import pythoncom
import sys
import pyfemap
from pyfemap import constants
import numpy as np
from functions.errors import check_error

def connect_to_femap():
    # Try making connection to Femap application
    try:
        exist_obj = pythoncom.connect(pyfemap.model.CLSID)
        app = pyfemap.model(exist_obj)
        print("Successfully connected to Femap.")
        return app
    except:
        sys.exit("Femap is not running. Please start Femap and try again.")


def find_plies(app, ply1_id1, gap, n_vecs, osID):

    '''
    Find the vector ids for all plies in a composite layup.
    
    Given the vector id for the first ply and the gap between the vector ids of each ply. 
    This is useful for automating post-processing of composite results in Femap, 
    where the output vectors for each ply follow a consistent naming convention.
    
    Args:
        app: The femap application object.
        ply1_id1: The vector id for the first ply and first output set.
        gap: The gap between the vector ids of each ply.
        n_vecs: The number of vectors for each ply. These are consecutive vector ids 
                starting from ply1_id1. For example, if n_vecs = 3, the vector ids 
                for the first ply are 16000001, 16000002, and 16000003.
        osID: The output set id to check for the existence of the vectors.
    
    Returns:
        numpy.ndarray: Array of vector ids that exist in the model.
        
    Author: Ahaan Bhosale
    '''

    # Create a result browsing object
    fr = app.feResults

    # Setup a layup object
    layup = app.feLayup

    # Count the number of plies
    nPlies = 0
    while layup.Next() == constants.FE_OK:
        nPlies += layup.NumberOfPlys

    # Get the possible vector ids
    ply1_ids = np.linspace(ply1_id1, ply1_id1+n_vecs-1, n_vecs, dtype=int)
    all_vec_ids = []
    for xi in range(nPlies):
        ply_vec_ids = ply1_ids + gap*xi
        all_vec_ids.append(ply_vec_ids)
    all_vec_ids = np.array(all_vec_ids).flatten()

    # Keep only the vector ids that exist in the model
    out_ids = np.array([], dtype=int)
    for vec_id in all_vec_ids:
        if fr.VectorExistsV2(osID, vec_id):
            out_ids = np.append(out_ids, vec_id)
    return out_ids


def create_output_vector(app, data, output_set_id, vec_name):

    '''
    This function creates a new output vector in Femap and populates it with the provided data.
    The vector id is automatically generated by Femap.
    input:
    - app: the femap application object.
    - data: a 2D numpy array where the first column contains the element ids and the second column contains the corresponding output values.
    - output_set_id: the id of the output set in femap where this vector will be added.
    - vec_name: the name of the new output vector to be created in femap.

    Author: Ahaan Bhosale
    '''

    # Create a result browsing object
    fr = app.feResults

    # Create a new output vector in femap for the new vector
    newVecID = fr.NonExistingUserVectorV2(output_set_id)
    rc, newColIdx = fr.AddScalarAtElemColumnV2(output_set_id, newVecID, vec_name, constants.FOT_ANY, False)
    check_error(rc)

    # Put the Python data back into this new column and save
    numVals = np.size(data, axis=0)
    rc = fr.SetColumn(newColIdx, numVals, data[:, 0], data[:, 1])
    check_error(rc)
    rc = fr.Save()
    check_error(rc)

    # Print to femap console
    message = "Succesfully created output vector: " + vec_name
    app.feAppMessage(0, message)